# Generated by Django 2.1.7 on 2019-08-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ended_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
