# Generated by Django 2.1.7 on 2019-08-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_ended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ended_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
